[book]
authors = ["Volker Hartmann", "Benedikt Heinrichs"]
language = "en"
multilingual = false
src = "src"
title = "Specification of Turntable API for Metadata Repositories"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
